heat_template_version: 2018-08-31

description: >
    Plantilla para el despliegue de 2 máquinas virtuales para los proyectos
    de ejemplo de la formación:
    - VM CirrOS (Nginx)
    - VM CirrOS (MariaDB)


# Claves SSH.

# Si las creo aquí... me temo que hay probabilidad de que queden por ahí!
# La claves las creo yo... y eso si, he de registrar la clave pública en el proyecto para que luego pueda usarla en la plantilla.
# El registro es lo que podría hacer aquí de la clave pública!
# Puedo generar esas claves con :
# $ ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa_proyecto           # Ese comando en windows? Nasti. puedo ir a un linux a generarlo..
# También lo puedo generar en un servicio web como https://www.ssh-keygen.com/ o https://www.ssh.com/ssh/keygen/ o github.com/ssh-keygen/ssh-keygen
# Pero en la descarga de la clave privada... ésta podría haber sido vulnerada
# Lo normal es que la clave prvada la genero en mi entorno.

# El cliente de openstack me genera clave clave keypair.. públic y privada... Solo que si uso esto, ya se registra en automático la pública en el proyecto... 
# Y está bien.. pero entonces no la pongo aquí como recurso.. la pongo como parámetro

# Resumen:

# OPCION 1: Si tengo claves ssh o las genero con algo com ssh-keygen... las genero en mi entorno... 
# y luego registro la clave pública en el proyecto de openstack. Y entonces la pongo aquí como recurso.
# OPCION 2: La genero con el cli de openstack... y entonces no la pongo aquí como recurso... 
# la pongo como parámetro... y el valor del parámetro es el nombre/ID de la clave que ya tengo registrada en el proyecto.

parameters:

    sabor_nginx:
      type:           string
      constraints:    
        - allowed_pattern: ^[a-zA-Z0-9._-]+$   # El nombre del sabor solo puede contener letras, números, puntos, guiones bajos y guiones medios.
          description: El nombre del sabor del nginx debe contener solo letras, números, puntos, guiones bajos y guiones medios.

    sabor_mariadb:
      type:           string
      constraints:    
        - allowed_pattern: ^[a-zA-Z0-9._-]+$   # El nombre del sabor solo puede contener letras, números, puntos, guiones bajos y guiones medios.
          description: El nombre del sabor del mariadb debe contener solo letras, números, puntos, guiones bajos y guiones medios.

    red_externa:
      type:           string
      constraints:    
        - allowed_pattern: ^[a-zA-Z0-9._-]+$   # El nombre de la red solo puede contener letras, números, puntos, guiones bajos y guiones medios.
          description: El nombre de la red externa (provider) debe contener solo letras, números, puntos, guiones bajos y guiones medios.
      description:     Nombre de la red externa (provider) para el gateway del router y la FIP

    imagen_mariadb:
      type:           string
      description:    ID de la imagen del mariadb en Glance
      constraints:    
        - allowed_pattern: ^[a-zA-Z0-9._-]+$   # El ID de la imagen solo puede contener letras, números, puntos, guiones bajos y guiones medios.
          description: El ID de la imagen del mariadb debe contener solo letras, números, puntos, guiones bajos y guiones medios.

    imagen_nginx:
      type:           string
      description:    ID de la imagen del nginx en Glance
      constraints:    
        - allowed_pattern: ^[a-zA-Z0-9._-]+$   # El ID de la imagen solo puede contener letras, números, puntos, guiones bajos y guiones medios.
          description: El ID de la imagen del nginx debe contener solo letras, números, puntos, guiones bajos y guiones medios.

    prefijo_nombre_recursos:
      type:           string
      description:    Prefijo para los nombres de los recursos (red, router, security groups, puertos, máquinas virtuales, etc...)
      constraints:    
        - allowed_pattern: ^[a-z-]+$   # El prefijo solo puede contener letras minúsculas y guiones.
          description: El prefijo para los nombres de los recursos debe contener solo letras minúsculas y guiones.

    cidr_subnet_middleware:
      type:           string
      description:    CIDR de la subnet del middleware (con DHCP)
      constraints:    
        - allowed_pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+$   # El CIDR debe tener el formato x.x.x.x/y donde x es un número entre 0 y 255 e y es un número entre 0 y 32.
          description: El CIDR de la subnet del middleware debe tener el formato x.x.x.x/y donde x es un número entre 0 y 255 e y es un número entre 0 y 32.
        
      default:        10.1.0.0/24

    gateway_subnet_middleware:
      type:           string
      description:    Gateway de la subnet del middleware
      constraints:    
        - allowed_pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$   # El gateway debe tener el formato x.x.x.x donde x es un número entre 0 y 255.
          description: El gateway de la subnet del middleware debe tener el formato x.x.x.x donde x es un número entre 0 y 255.
      default:        10.1.0.1

    cidr_subnet_backend:
      type:           string
      description:    CIDR de la subnet del backend (sin DHCP)
      constraints:    
        - allowed_pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+$   # El CIDR debe tener el formato x.x.x.x/y donde x es un número entre 0 y 255 e y es un número entre 0 y 32.
          description: El CIDR de la subnet del backend debe tener el formato x.x.x.x/y donde x es un número entre 0 y 255 e y es un número entre 0 y 32.
      default:        10.2.0.0/24

    gateway_subnet_backend:
      type:           string
      description:    Gateway de la subnet del backend
      constraints:    
        - allowed_pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$   # El gateway debe tener el formato x.x.x.x donde x es un número entre 0 y 255.
          description: El gateway de la subnet del backend debe tener el formato x.x.x.x donde x es un número entre 0 y 255.
      default:         10.2.0.1

    numeros_puerto_nginx:
      type:           comma_delimited_list     # Donde pondremos una lista que heat interpreta como strings
                                               # No hay lista de numeros.
      description:    Números de puerto del nginx (separados por comas)
      constraints:    
        - allowed_pattern: ^([0-9]{1,5},)*[0-9]{1,5}$   # La lista de números de puerto debe tener el formato x,x,x donde x es un número entre 1 y 65535.
          description: La lista de números de puerto del nginx debe tener el formato x,x,x donde x es un número entre 1 y 65535.
      default:        80,443

    numero_puerto_mariadb:
      type:           number
      constraints:    
        - range:      [1, 65535]
          description: El número de puerto del mariadb debe estar entre 1 y 65535
      default:        3306
      # Es importante poner estos constrains? IMPORTANTISIMO!

      # Validar el valor que el usuario de la plantilla suministrará al ejecutarla.
      # Si ejecuta la plantilla con un valor inválido, el despliegue de la plantilla fallará.

      # Si no pongo este constrain, que ocurrirá si el usuario escriobe 2000000 como número de puerto del mariadb?
      # El despliegue funcionará? NO
      # Al crear el recurso del puerto dará error.

      # Aunque ponga un valor inválido, el recurso no se creará... y eso está bien.
      # El problema o la diferencia está en CUANDO TENGO EL ERROR!
      # Si pongo constrain, el error lo tendré antes de que se cree ningún recurso. Lo primero que hará heat es aplicar los constrains a los parámetros. 
      # Si alguno de los parámetros no cumple su constrain, el despliegue fallará sin haber llegado a crear ningún recurso. 

      # Si no pongo constrain, el error lo tendré durante la creación del recurso. 
      # Que quizás es el décimo recurso en ser creado.
      # Resultado: Dejo una infra creada a medias. Mola eso en un entorno de prod? NO!

      # Todo lo que pueda cortar de inicio, lo corto. Para evitar mierderios en medio de un despliegue.
      # Además estamos suponiendo que estamos creando la infra!
      # Y si lo que estamos es upgradeaándola? 
      # Y actualizo la mitad de la infra (de pro) y la otra mitad la dejo sin actualizar porque el despliegue falla por un error en un parámetro...
      # Y dejo la infra de prod JODIDA!
      # ESO SI QUE NO MOLA NADA DE NADA!

      # HEAT ... es bastante cutre con los constrains que se pueden definir.
      # Con el caso de los puertos de nginx (que son una lista...de textos)... estamos JODIDOS!

      # Las capacidades de validación de Terraform, son una locura comparadas con las de HEAT.

resources:

    clave_ssh:
      type:                 OS::Nova::KeyPair
      properties:
        name:           #mi-clave-ssh# Quiero ponerle el prefijo
          # Funciones de plantilla. HEAT tiene muchas funciones de plantilla para manipular strings, listas, números, etc... y para referenciar recursos y parámetros.
          str_replace:
            template:       PREFIJO-mi-clave-ssh
            params:
              PREFIJO: 
                get_param:  prefijo_nombre_recursos 
        public_key:         # La clave pública me la pasan por parámetro... porque la genero yo en mi entorno... y la registro en el proyecto de openstack... y aquí solo pongo el nombre de esa clave registrada.
          get_param:        clave_ssh_publica
        type:               ssh

  # Cuando apliquemos esta plantilla, eso de ahí arriba se convertirá en algo así como:
  # $ openstack keypair create --public-key ~/.ssh/id_rsa_proyecto.pub ---type ssh mi-proyecto-mi-clave-ssh
  # Realmente se transforma en ese comando? en veces si ... en veces no! depende del estado real.
  # Si ya existe y tiene los mismos atributos, no hará nada.
  # Si no existe lo creará (ejecutará literalmente ese comando)
  # Si existe pero tiene atributos diferentes, lo que ejecutará es:
  # $ openstack keypair delete mi-proyecto-mi-clave-ssh
  # $ openstack keypair create --public-key ~/.ssh/id_rsa_proyecto.pub ---type ssh mi-proyecto-mi-clave-ssh
  # Es decir, eliminará la clave que ya existe y creará la nueva con los atributos que le he puesto en la plantilla.
  # Ya que el recurso de clave ssh no es actualizable, lo que hace heat es eliminarlo y volverlo a crear con los nuevos atributos.
  # Es decir, es ese comando u otros y con 30 ifs... 


    net_privada:
      type: OS::Neutron::Net
      properties:
        name:
          str_replace:
            template: PREFIJO-red-privada
            params:
              PREFIJO: { get_param: prefijo_nombre_recursos }

    subnet_middleware:
        type: OS::Neutron::Subnet
        properties:
          name:
            str_replace:
              template: PREFIJO-subnet-middleware
              params:
                PREFIJO: { get_param: prefijo_nombre_recursos }
          network:       { get_resource: net_privada }
          cidr:          { get_param: cidr_subnet_middleware }
          gateway_ip:    { get_param: gateway_subnet_middleware }
          enable_dhcp:   true
          dns_nameservers:
                        - 8.8.8.8

    subnet_backend:

    router:

    security_group_nginx:

    puerto_nginx:

    security_group_mariadb:     # numero_puerto_mariadb

    puerto_mariadb:

    vm_nginx:

    ip_flotante_nginx:

    asigancion_ip_flotante_nginx:

    vm_mariadb:

outputs:

    id_red_privada:

    id_subnet_middleware:

    id_subnet_backend:

    id_router:

    id_security_group_nginx:

    id_puerto_nginx:

    id_security_group_mariadb:

    id_puerto_mariadb:

    id_vm_nginx:

    ip_flotante_nginx:

    id_vm_mariadb:

    ip_interna_vm_nginx:

    ip_interna_vm_mariadb:

    ip_flotante_vm_nginx:

    cidr_subnet_middleware:

    cidr_subnet_backend:

    numeros_puerto_nginx:

    numero_puerto_mariadb:
